services:
  postgres:
    image: postgres:17-alpine
    restart: always
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # backend:
  #   build: .
  #   command: sh -c "./sentinel"
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8080:8080"
volumes:
  postgres_data:
