// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: apache_log.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApacheLogRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Raw               string                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	ClientIp          string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	RemoteLogname     string                 `protobuf:"bytes,3,opt,name=remote_logname,json=remoteLogname,proto3" json:"remote_logname,omitempty"`
	AuthenticatedUser string                 `protobuf:"bytes,4,opt,name=authenticated_user,json=authenticatedUser,proto3" json:"authenticated_user,omitempty"`
	Timestamp         string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Method            string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	RequestUri        string                 `protobuf:"bytes,7,opt,name=request_uri,json=requestUri,proto3" json:"request_uri,omitempty"`
	Protocol          string                 `protobuf:"bytes,8,opt,name=protocol,proto3" json:"protocol,omitempty"`
	StatusCode        int32                  `protobuf:"varint,9,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ResponseSize      int64                  `protobuf:"varint,10,opt,name=response_size,json=responseSize,proto3" json:"response_size,omitempty"`
	Referer           string                 `protobuf:"bytes,11,opt,name=referer,proto3" json:"referer,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApacheLogRequest) Reset() {
	*x = ApacheLogRequest{}
	mi := &file_apache_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApacheLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApacheLogRequest) ProtoMessage() {}

func (x *ApacheLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apache_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApacheLogRequest.ProtoReflect.Descriptor instead.
func (*ApacheLogRequest) Descriptor() ([]byte, []int) {
	return file_apache_log_proto_rawDescGZIP(), []int{0}
}

func (x *ApacheLogRequest) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *ApacheLogRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *ApacheLogRequest) GetRemoteLogname() string {
	if x != nil {
		return x.RemoteLogname
	}
	return ""
}

func (x *ApacheLogRequest) GetAuthenticatedUser() string {
	if x != nil {
		return x.AuthenticatedUser
	}
	return ""
}

func (x *ApacheLogRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ApacheLogRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ApacheLogRequest) GetRequestUri() string {
	if x != nil {
		return x.RequestUri
	}
	return ""
}

func (x *ApacheLogRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ApacheLogRequest) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ApacheLogRequest) GetResponseSize() int64 {
	if x != nil {
		return x.ResponseSize
	}
	return 0
}

func (x *ApacheLogRequest) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

type ApacheLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApacheLogResponse) Reset() {
	*x = ApacheLogResponse{}
	mi := &file_apache_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApacheLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApacheLogResponse) ProtoMessage() {}

func (x *ApacheLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apache_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApacheLogResponse.ProtoReflect.Descriptor instead.
func (*ApacheLogResponse) Descriptor() ([]byte, []int) {
	return file_apache_log_proto_rawDescGZIP(), []int{1}
}

func (x *ApacheLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_apache_log_proto protoreflect.FileDescriptor

const file_apache_log_proto_rawDesc = "" +
	"\n" +
	"\x10apache_log.proto\x12\n" +
	"apache_log\"\xea\x02\n" +
	"\x10ApacheLogRequest\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\tR\x03raw\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12%\n" +
	"\x0eremote_logname\x18\x03 \x01(\tR\rremoteLogname\x12-\n" +
	"\x12authenticated_user\x18\x04 \x01(\tR\x11authenticatedUser\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x1f\n" +
	"\vrequest_uri\x18\a \x01(\tR\n" +
	"requestUri\x12\x1a\n" +
	"\bprotocol\x18\b \x01(\tR\bprotocol\x12\x1f\n" +
	"\vstatus_code\x18\t \x01(\x05R\n" +
	"statusCode\x12#\n" +
	"\rresponse_size\x18\n" +
	" \x01(\x03R\fresponseSize\x12\x18\n" +
	"\areferer\x18\v \x01(\tR\areferer\"-\n" +
	"\x11ApacheLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2Z\n" +
	"\x10ApacheLogService\x12F\n" +
	"\aSendLog\x12\x1c.apache_log.ApacheLogRequest\x1a\x1d.apache_log.ApacheLogResponseB\tZ\a.;protob\x06proto3"

var (
	file_apache_log_proto_rawDescOnce sync.Once
	file_apache_log_proto_rawDescData []byte
)

func file_apache_log_proto_rawDescGZIP() []byte {
	file_apache_log_proto_rawDescOnce.Do(func() {
		file_apache_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apache_log_proto_rawDesc), len(file_apache_log_proto_rawDesc)))
	})
	return file_apache_log_proto_rawDescData
}

var file_apache_log_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apache_log_proto_goTypes = []any{
	(*ApacheLogRequest)(nil),  // 0: apache_log.ApacheLogRequest
	(*ApacheLogResponse)(nil), // 1: apache_log.ApacheLogResponse
}
var file_apache_log_proto_depIdxs = []int32{
	0, // 0: apache_log.ApacheLogService.SendLog:input_type -> apache_log.ApacheLogRequest
	1, // 1: apache_log.ApacheLogService.SendLog:output_type -> apache_log.ApacheLogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apache_log_proto_init() }
func file_apache_log_proto_init() {
	if File_apache_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apache_log_proto_rawDesc), len(file_apache_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apache_log_proto_goTypes,
		DependencyIndexes: file_apache_log_proto_depIdxs,
		MessageInfos:      file_apache_log_proto_msgTypes,
	}.Build()
	File_apache_log_proto = out.File
	file_apache_log_proto_goTypes = nil
	file_apache_log_proto_depIdxs = nil
}
