// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: apache_log.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApacheLogService_SendLog_FullMethodName = "/apache_log.ApacheLogService/SendLog"
)

// ApacheLogServiceClient is the client API for ApacheLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApacheLogServiceClient interface {
	SendLog(ctx context.Context, in *ApacheLogRequest, opts ...grpc.CallOption) (*ApacheLogResponse, error)
}

type apacheLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApacheLogServiceClient(cc grpc.ClientConnInterface) ApacheLogServiceClient {
	return &apacheLogServiceClient{cc}
}

func (c *apacheLogServiceClient) SendLog(ctx context.Context, in *ApacheLogRequest, opts ...grpc.CallOption) (*ApacheLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApacheLogResponse)
	err := c.cc.Invoke(ctx, ApacheLogService_SendLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApacheLogServiceServer is the server API for ApacheLogService service.
// All implementations must embed UnimplementedApacheLogServiceServer
// for forward compatibility.
type ApacheLogServiceServer interface {
	SendLog(context.Context, *ApacheLogRequest) (*ApacheLogResponse, error)
	mustEmbedUnimplementedApacheLogServiceServer()
}

// UnimplementedApacheLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApacheLogServiceServer struct{}

func (UnimplementedApacheLogServiceServer) SendLog(context.Context, *ApacheLogRequest) (*ApacheLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLog not implemented")
}
func (UnimplementedApacheLogServiceServer) mustEmbedUnimplementedApacheLogServiceServer() {}
func (UnimplementedApacheLogServiceServer) testEmbeddedByValue()                          {}

// UnsafeApacheLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApacheLogServiceServer will
// result in compilation errors.
type UnsafeApacheLogServiceServer interface {
	mustEmbedUnimplementedApacheLogServiceServer()
}

func RegisterApacheLogServiceServer(s grpc.ServiceRegistrar, srv ApacheLogServiceServer) {
	// If the following call pancis, it indicates UnimplementedApacheLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApacheLogService_ServiceDesc, srv)
}

func _ApacheLogService_SendLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApacheLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApacheLogServiceServer).SendLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApacheLogService_SendLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApacheLogServiceServer).SendLog(ctx, req.(*ApacheLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApacheLogService_ServiceDesc is the grpc.ServiceDesc for ApacheLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApacheLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apache_log.ApacheLogService",
	HandlerType: (*ApacheLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendLog",
			Handler:    _ApacheLogService_SendLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apache_log.proto",
}
